---
apiVersion: app/v1
kind: Deployment
metadata:
  name: node-deployment
spec:
  selector:
    matchLabel:
      app: node
  replicas: 2
  template:
    matadata:
      labels:
        app: node
    spec:
      containers:
      - name: node
        image: devarangan:1.0
      ports:
      - containerPort: 4000
---
apiVersion: v1
kind: Service
metadata:
  name: node-service
spec:
  selector:
    app: node
  ports:
  - protocol: TCP
    port: 80
    targetPort: 4000
    nodePort: 30000
    type: NodePort
