---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-backend-application
spec:
  selector:
    matchLabels:
      app: portfolio-backend
  replicas: 2
  template:
    metadata:
      labels:
        app: portfolio-backend
    spec:
      containers:
      - name: portfolio-backend
        image: devarangan/nodejs
        env:
            - name: MONGO_HOST
              value: mongodb
            - name: MONGO_PORT
              value: "27017"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: portfolio-backend-service
spec:
  selector:
    app: portfolio-backend
  ports:
  - protocol: TCP
    port: 80
    targetPort: 8080
    nodePort: 31000
  type: NodePort
